// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKaZCVIyz15xg6KX0eG0_yabudNWp-ebQ',
    appId: '1:955105328890:web:ea36760ea80d4400d69343',
    messagingSenderId: '955105328890',
    projectId: 'ditonton-11d9f',
    authDomain: 'ditonton-11d9f.firebaseapp.com',
    storageBucket: 'ditonton-11d9f.appspot.com',
    measurementId: 'G-L52PX3FZR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI_5glj24ChDfnusibpQX8SSkHXOj7TU8',
    appId: '1:955105328890:android:cebc659990845e00d69343',
    messagingSenderId: '955105328890',
    projectId: 'ditonton-11d9f',
    storageBucket: 'ditonton-11d9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfzxJ411XD_bHPM4w2fu_PcRcNDlW7Nk',
    appId: '1:955105328890:ios:c25624d3516dfb84d69343',
    messagingSenderId: '955105328890',
    projectId: 'ditonton-11d9f',
    storageBucket: 'ditonton-11d9f.appspot.com',
    iosClientId:
        '955105328890-1op2f4p00b6shdiibmvudaq8hhunsoag.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
